<?php
$newsArr = array(
    '3.131 2022-01-19' => array(
       
        array( 'k'=>'New',  'm'=>'MAC, POR > new field: "Deviation" to reflect Production problem documentation.'),
    ),
    '3.128 2021-10-31' => array(
        array( 'k'=>'Improved',  'm'=>'Error Message boxes improved.'),
        array( 'k'=>'New',  'm'=>'DB-structure new table PUR (Purchase prequesition).'),
    ),
    '3.127 2021-10-31' => array(
        array( 'k'=>'Improved',  'm'=>'Improved User Plugin Favorites: support full parameterization of the favs.'),
        array( 'k'=>'Improved',  'm'=>'DB-structure upgrade table:USER_PREF2: more support for user configurations.'),
    ),
    '3.124 2021-09-27' => array(
        array( 'k'=>'Improved',  'm'=>'DB-structure upgrade table:SUC_BOM: allow adding more than one MAC-component with the same MAA.'),
    ),
    '3.121 2021-06-10' => array(
        array( 'k'=>'Improved',  'm'=>'Password storage improved (salt introduced for local passwords).'),
    ),
    '3.112 2021-02-19' => array(
        array( 'k'=>'Improved', 't'=>'ABSTRACT_PROTO', 'm'=>'increased sub-levels for protocol steps.'),
    ),
    '3.103 2020-06-03' => array(
        array( 'k'=>'New', 'm'=>'Activated the "Lab Specic Release Policy"'),
    ),
    '3.103 2020-05-10' => array(
        array( 'k'=>'New', 't'=>'ABSTRACT_PROTO', 'm'=>'Improved Protocol template Editor'),
        
        
    ),
    '3.000 2019-01-03' => array(
        array( 'k'=>'New', 'm'=>'Setup a new fork for Blink'),
        
        
    ),
    
    
);
