<?

define ("PaXML_XMLVERSION",                 "0.7");
define ("PaXML_XMLVERSION_MIN",             "0.7");  // minimal version for IMPORT


// list of tags
define("PaXMLTag_PARTISANXML",              "partisanxml");
define("PaXMLTag_OBJECT",                   "object");
define("PaXMLTag_OPTION",                   "option");
define("PaXMLTag_CLASS",                    "class");
define("PaXMLTag_CLASSATTRIBUTES",          "attributes");
define("PaXMLTag_CLASSATTRIBUTE",           "attribute");
define("PaXMLTag_PARAMETERS",               "parameters");
define("PaXMLTag_PARAMETER",                "parameter");
define("PaXMLTag_ASSOCIATIVES",             "elements");
define("PaXMLTag_ASSOCIATIVE",              "element");

//define("PaXMLTag_VARIOS",                   "varios");
//define("PaXMLTag_VARIO",                    "vario");



define("PaXMLTag_PARTISANXML_VERSION",      "version");
define("PaXMLTag_PARTISANXML_DB",           "db");
define("PaXMLTag_PARTISANXML_DBVERSION",    "dbversion");	// e.g. 1.0.3.3

define("PaXMLTag_OBJECT_TYPE",              "type");
define("PaXMLTag_OBJECT_WIID",              "wiid");
define("PaXMLTag_OBJECT_ROID",              "roid");
define("PaXMLTag_OBJECT_CREATION_DATE",     "creation_date");
define("PaXMLTag_OBJECT_MODIFICATION_DATE", "modification_date");
define("PaXMLTag_OBJECT_CREATOR", 			"creator");
define("PaXMLTag_OBJECT_MODIFIER", 			"modifier");

define("PaXMLTag_OBJECT_FIELDID",           "fieldID");
define("PaXMLTag_OBJECT_ATTACH",            "attach");

define("PaXMLTag_PARAMETERS_CLASS",          "class");


define("PaXMLTag_PARAMETER_NAME",           "name");
define("PaXMLTag_PARAMETER_TYPE",           "type");
define("PaXMLTag_PARAMETER_VARIO",          "vario"); // since 2020-03-10 support S_VARIO export

define("PaXMLTag_CLASS_NAME",               "name");
define("PaXMLTag_CLASS_TYPE",               "type");

define("PaXMLTag_CLASSATTRIBUTE_NAME",      "name");

define("PaXMLTag_OPTION_NAME",              "name");
define("PaXMLTag_OPTION_TYPE",              "type");

define("PaXMLTag_ASSOCIATIVES_TYPE",        "type");

define("PaXMLTag_ASSOCIATIVE_CLASS",        "class");
define("PaXMLTag_ASSOCIATIVE_FILE",         "file");




?>
